import { db, businessesTable } from "./index.ts";
import { eq, count } from "drizzle-orm";

interface BusinessSeed {
    name: string;
    address?: string;
    phone?: string;
    website?: string;
    sector: string;
    rating?: number;
    reviewCount?: number;
    mapsUrl?: string;
    priority: "high" | "medium" | "low";
    routeDay?: number;
    isBonus: boolean;
    buildingGroup?: string | null;
    callType?: "walk_in" | "cold_call";
  }

const BUSINESSES: BusinessSeed[] = [
  // ── DAY 1 — North Minneapolis + Brooklyn Center + Columbia Heights ──
  {
    name: "Central Roofing Company",
    address: "4550 Main St NE, Minneapolis, MN 55421",
    phone: "(763) 572-0660",
    sector: "ROOFING",
    rating: 4.5,
    reviewCount: 61,
    mapsUrl: "https://maps.google.com/?cid=1111272801552340184",
    priority: "high",
    routeDay: 1,
    isBonus: false,
    buildingGroup: null,
  },
  {
    name: "Bolechowski Construction",
    address: "3031 Croft Dr, Minneapolis, MN 55418",
    phone: "(612) 965-1509",
    sector: "GENERAL CONTRACTOR",
    rating: 4.8,
    reviewCount: 66,
    mapsUrl: "https://maps.google.com/?cid=4676986517101676837",
    priority: "high",
    routeDay: 1,
    isBonus: false,
    buildingGroup: null,
  },
  {
    name: "Roof Repair PHD",
    address: "3201 N Humboldt Ave, Minneapolis, MN 55412",
    phone: "(612) 418-4240",
    sector: "ROOFING",
    rating: 5,
    reviewCount: 54,
    mapsUrl: "https://maps.google.com/?cid=18040947368546163432",
    priority: "high",
    routeDay: 1,
    isBonus: false,
    buildingGroup: null,
  },
  {
    name: "Johnny Five Construction",
    address: "338 24th Ave NE, Minneapolis, MN 55418",
    phone: "(612) 293-5778",
    sector: "GENERAL CONTRACTOR",
    rating: 5,
    reviewCount: 19,
    mapsUrl: "https://maps.google.com/?cid=18040947368546163432",
    priority: "medium",
    routeDay: 1,
    isBonus: false,
    buildingGroup: null,
  },
  // Day 1 Bonus
  {
    name: "Paris Painting",
    address: "3515 48th Ave N, Brooklyn Center, MN 55429",
    phone: "(763) 515-4463",
    sector: "PAINTING",
    rating: 4.8,
    reviewCount: 868,
    mapsUrl: "https://paris-painting.com/",
    priority: "medium",
    routeDay: 1,
    isBonus: true,
    buildingGroup: null,
  },
  {
    name: "Edison Electric",
    address: "3134 California St NE #126, Minneapolis, MN 55418",
    phone: "(612) 441-2728",
    sector: "ELECTRICAL",
    rating: 4.9,
    reviewCount: 1029,
    mapsUrl: "https://www.electrician-minneapolis.com/",
    priority: "medium",
    routeDay: 1,
    isBonus: true,
    buildingGroup: null,
  },

  // ── DAY 2 — South Minneapolis + Nokomis + Richfield ──
  {
    name: "Garlock-French Corporation",
    address: "2301 E 25th St, Minneapolis, MN 55406",
    phone: "(612) 722-7129",
    sector: "ROOFING",
    rating: 4.7,
    reviewCount: 143,
    mapsUrl: "https://maps.google.com/?cid=13692711712261859388",
    priority: "high",
    routeDay: 2,
    isBonus: false,
    buildingGroup: null,
  },
  {
    name: "Nokomis Roofing",
    address: "5053 36th Ave S, Minneapolis, MN 55417",
    phone: "(612) 221-4736",
    sector: "ROOFING",
    rating: 4.7,
    reviewCount: 58,
    mapsUrl: "https://maps.google.com/?cid=8685256349586553152",
    priority: "high",
    routeDay: 2,
    isBonus: false,
    buildingGroup: null,
  },
  {
    name: "Liberte Construction",
    address: "1406 W Lake St Suite 202, Minneapolis, MN 55408",
    phone: "(612) 712-6420",
    sector: "REMODELING",
    rating: 4.9,
    reviewCount: 205,
    mapsUrl: "https://maps.google.com/?cid=3271339792345538938",
    priority: "medium",
    routeDay: 2,
    isBonus: false,
    buildingGroup: null,
  },
  {
    name: "3 Bears Landscaping",
    address: "3916 Cheatham Ave, Minneapolis, MN 55406",
    phone: "(612) 806-3012",
    sector: "LANDSCAPING",
    rating: 4.8,
    reviewCount: 179,
    mapsUrl: "https://3bearslandscaping.com/",
    priority: "medium",
    routeDay: 2,
    isBonus: false,
    buildingGroup: null,
  },
  // Day 2 Bonus
  {
    name: "Roell Painting Company",
    address: "7301 Penn Ave S, Minneapolis, MN 55423",
    phone: "(763) 559-5296",
    sector: "PAINTING",
    rating: 4.9,
    reviewCount: 388,
    mapsUrl: "https://www.roellpainting.com/",
    priority: "medium",
    routeDay: 2,
    isBonus: true,
    buildingGroup: null,
  },
  {
    name: "Bratt Tree",
    address: "2423 E 26th St, Minneapolis, MN 55406",
    phone: "(612) 429-3904",
    sector: "TREE SERVICE",
    rating: 4.8,
    reviewCount: 440,
    mapsUrl: "https://www.bratttree.com/",
    priority: "medium",
    routeDay: 2,
    isBonus: true,
    buildingGroup: null,
  },
  {
    name: "Vineland Tree Care",
    address: "2504 25th Ave S, Minneapolis, MN 55406",
    phone: "(612) 872-0205",
    sector: "TREE SERVICE",
    rating: 4.9,
    reviewCount: 461,
    mapsUrl: "http://www.vinelandtree.com/",
    priority: "medium",
    routeDay: 2,
    isBonus: true,
    buildingGroup: null,
  },
  {
    name: "Big Mike's Gutters",
    address: "235 N Irving Ave, Minneapolis, MN 55405",
    phone: "(612) 275-2222",
    sector: "GUTTERS",
    rating: 4.7,
    reviewCount: 201,
    mapsUrl: "https://bigmikesgutters.net/",
    priority: "medium",
    routeDay: 2,
    isBonus: true,
    buildingGroup: null,
  },

  // ── DAY 3 — Bloomington + South Suburbs ──
  {
    name: "Twin Cities Contracting Services",
    address: "140 W 98th St #202, Bloomington, MN 55420",
    phone: "(952) 405-6201",
    sector: "GENERAL CONTRACTOR",
    rating: 5,
    reviewCount: 485,
    mapsUrl: "https://maps.google.com/?cid=2264026134366600485",
    priority: "high",
    routeDay: 3,
    isBonus: false,
    buildingGroup: null,
  },
  {
    name: "R & R Roofing Inc.",
    address: "8609 Lyndale Ave S, Bloomington, MN 55420",
    phone: "(952) 210-4988",
    sector: "ROOFING",
    rating: 5,
    reviewCount: 312,
    mapsUrl: "https://maps.google.com/?cid=1779344381757415722",
    priority: "high",
    routeDay: 3,
    isBonus: false,
    buildingGroup: null,
  },
  {
    name: "Snap Construction Inc.",
    address: "951 American Blvd E, Minneapolis, MN 55420",
    phone: "(612) 333-7627",
    sector: "GENERAL CONTRACTOR",
    rating: 4.9,
    reviewCount: 419,
    mapsUrl: "https://www.snapconstruction.com/",
    priority: "high",
    routeDay: 3,
    isBonus: false,
    buildingGroup: "951-american-blvd-e",
  },
  {
    name: "Your Home Improvement Company",
    address: "9555 James Ave S #250, Bloomington, MN 55431",
    phone: "(952) 522-3088",
    sector: "HOME IMPROVEMENT",
    rating: 4.7,
    reviewCount: 584,
    mapsUrl: "https://www.yourhomeimprovementco.com/",
    priority: "high",
    routeDay: 3,
    isBonus: false,
    buildingGroup: null,
  },
  // Day 3 Bonus
  {
    name: "USA Insulation of Minneapolis",
    address: "8055 Ranchers Rd NE, Minneapolis, MN 55432",
    phone: "(612) 767-3030",
    sector: "INSULATION",
    rating: 5,
    reviewCount: 564,
    mapsUrl: "https://usainsulation.com/minneapolis/",
    priority: "medium",
    routeDay: 3,
    isBonus: true,
    buildingGroup: null,
  },
  {
    name: "Affordable Insulation",
    address: "951 American Blvd E, Bloomington, MN 55420",
    phone: "(612) 435-2780",
    sector: "INSULATION",
    rating: 4.9,
    reviewCount: 128,
    mapsUrl: "http://www.affordableinsulationmn.com/",
    priority: "medium",
    routeDay: 3,
    isBonus: true,
    buildingGroup: "951-american-blvd-e",
  },

  // ── DAY 4 — St. Louis Park + West Suburbs ──
  {
    name: "Sela Roofing & Remodeling",
    address: "4521 MN-7 Suite A, Minneapolis, MN 55416",
    phone: "(612) 482-8213",
    sector: "ROOFING",
    rating: 5,
    reviewCount: 647,
    mapsUrl: "https://maps.google.com/?cid=15297467086839306215",
    priority: "high",
    routeDay: 4,
    isBonus: false,
    buildingGroup: null,
  },
  {
    name: "Minnesota Roofing Company",
    address: "1071 County Hwy 10 Ste 230, Spring Lake Park, MN 55432",
    phone: "(612) 888-7663",
    sector: "ROOFING",
    rating: 4.8,
    reviewCount: 262,
    mapsUrl: "https://maps.google.com/?cid=3330275434023154631",
    priority: "high",
    routeDay: 4,
    isBonus: false,
    buildingGroup: null,
  },
  {
    name: "Blue Yeti HVAC & Plumbing",
    address: "6325 Cambridge St #2, St Louis Park, MN 55416",
    phone: "(952) 209-7360",
    sector: "HVAC",
    rating: 4.9,
    reviewCount: 671,
    mapsUrl: "https://maps.google.com/?cid=2264026134366600485",
    priority: "high",
    routeDay: 4,
    isBonus: false,
    buildingGroup: "6325-cambridge-st",
  },
  // Day 4 Bonus
  {
    name: "Harrison Electric",
    address: "3440 Kilmer Ln N, Minneapolis, MN 55441",
    phone: "(763) 544-3300",
    sector: "ELECTRICAL",
    rating: 4.8,
    reviewCount: 959,
    mapsUrl: "https://harrison-electric.com/",
    priority: "medium",
    routeDay: 4,
    isBonus: true,
    buildingGroup: null,
  },
  {
    name: "ONYX Plumbing & Gas",
    address: "6325 Cambridge St #7, Minneapolis, MN 55416",
    phone: "(612) 234-6699",
    sector: "PLUMBING",
    rating: 4.9,
    reviewCount: 115,
    mapsUrl: "https://calltheonyx.com/",
    priority: "medium",
    routeDay: 4,
    isBonus: true,
    buildingGroup: "6325-cambridge-st",
  },
  // ── COLD CALL LIST — 75 mid-size service businesses (phone-only prospects) ──
  {
    name: "Hero Plumbing, Heating, Cooling & Electrical",
    address: "10900 Hampshire Ave S #120, Bloomington",
    phone: "(612) 504-1620",
    website: "callhero.com",
    sector: "HVAC",
    rating: 4.7,
    reviewCount: 18342,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Standard Heating & Air Conditioning",
    address: "130 Plymouth Ave N, Minneapolis",
    phone: "(612) 824-2656",
    website: "standardheating.com",
    sector: "HVAC",
    rating: 4.9,
    reviewCount: 6603,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Randy's Electric & Plumbing",
    address: "13400 67th Ave N, Maple Grove",
    phone: "(612) 712-4183",
    website: "randyselectric.com",
    sector: "ELECTRICAL",
    rating: 4.8,
    reviewCount: 6230,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Pronto Heating and Air Conditioning",
    address: "7415 Cahill Rd, Minneapolis",
    phone: "(952) 835-7777",
    website: "prontoheat.com",
    sector: "HVAC",
    rating: 4.9,
    reviewCount: 5505,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Blue Ox Heating & Air",
    address: "5720 International Pkwy, Minneapolis",
    phone: "(651) 300-1636",
    website: "goblueox.com",
    sector: "HVAC",
    rating: 4.8,
    reviewCount: 4052,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "EarlyBird Electric",
    address: "5720 International Pkwy, New Hope",
    phone: "(612) 217-7756",
    website: "earlybirdelectricians.com",
    sector: "ELECTRICAL",
    rating: 4.8,
    reviewCount: 3572,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Total Comfort Heating & Cooling",
    address: "8818 7th Ave N, Golden Valley",
    phone: "(763) 299-7433",
    website: "tcomfort.com",
    sector: "HVAC",
    rating: 4.8,
    reviewCount: 3379,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Home Energy Heating & Cooling",
    address: "2415 Annapolis Ln N #170, Plymouth",
    phone: "(763) 200-1886",
    website: "homeenergycenter.com",
    sector: "HVAC",
    rating: 4.9,
    reviewCount: 3246,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "All American Door Co.",
    address: "1634 County Hwy 10 #6, Minneapolis",
    phone: "(763) 244-1605",
    website: "allamericandoormn.com",
    sector: "GARAGE DOORS",
    rating: 4.9,
    reviewCount: 2703,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Metro Heating & Cooling",
    address: "1220 Cope Ave E, Maplewood",
    phone: "(651) 294-7798",
    website: "metroheating.net",
    sector: "HVAC",
    rating: 4.9,
    reviewCount: 2203,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "A1 Garage Door Service",
    address: "3801 W 50th St #250b, Minneapolis",
    phone: "(612) 238-5253",
    website: "a1garage.com",
    sector: "GARAGE DOORS",
    rating: 4.9,
    reviewCount: 1828,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Plunkett's Pest Control",
    address: "40 52nd Way NE, Fridley",
    phone: "(763) 265-7812",
    website: "plunketts.net",
    sector: "PEST CONTROL",
    rating: 4.8,
    reviewCount: 1451,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Rove Pest Control",
    address: "301 4th Ave S #272h, Minneapolis",
    phone: "(763) 400-8989",
    website: "rovepestcontrol.com",
    sector: "PEST CONTROL",
    rating: 4.9,
    reviewCount: 1370,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Superior Garage Door Repair",
    address: "1405 Lilac Dr N #160B, Minneapolis",
    phone: "(612) 999-1228",
    website: "247superiorgaragedoor.com",
    sector: "GARAGE DOORS",
    rating: 4.9,
    reviewCount: 1326,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Northland Fence",
    address: "7703 Main St NE, Fridley",
    phone: "(763) 373-4906",
    website: "northlandfence.com",
    sector: "FENCING/DECKS",
    rating: 4.9,
    reviewCount: 1208,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Stafford Home Service",
    address: "6225 Cambridge St, Minneapolis",
    phone: "(612) 895-6883",
    website: "staffordhomeservice.com",
    sector: "HVAC",
    rating: 4.9,
    reviewCount: 1160,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Champion Replacement Windows",
    address: "5100 US-169 N Suite B, New Hope",
    phone: "(763) 515-8426",
    website: "championwindow.com",
    sector: "WINDOWS",
    rating: 4.5,
    reviewCount: 1015,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Countryside Heating & Cooling",
    address: "1960 County Rd 90 #200, Maple Plain",
    phone: "(763) 299-9996",
    website: "countryside-solutions.com",
    sector: "HVAC",
    rating: 4.9,
    reviewCount: 1013,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Bloomington Heating & Air",
    address: "1101 W 80th St, Bloomington",
    phone: "(952) 395-5808",
    website: "bloomingtonheating.com",
    sector: "HVAC",
    rating: 5,
    reviewCount: 956,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Advantage Electric",
    address: "9257 W River Rd, Minneapolis",
    phone: "(612) 751-1772",
    website: "advantageelectricmn.com",
    sector: "ELECTRICAL",
    rating: 5,
    reviewCount: 939,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Valor Pest Solutions",
    address: "530 N 3rd St Unit C, Minneapolis",
    phone: "(763) 777-7010",
    website: "valorpestsolutions.com",
    sector: "PEST CONTROL",
    rating: 4.9,
    reviewCount: 863,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Rainbow Lawncare",
    address: "11571 K-Tel Dr, Minnetonka",
    phone: "(952) 252-0535",
    website: "rainbowlawncare.com",
    sector: "LANDSCAPING",
    rating: 4.8,
    reviewCount: 601,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "NMC Exteriors / Apple Roofing",
    address: "14505 21st Ave N #226, Plymouth",
    phone: "(763) 325-1439",
    website: "appleroof.com",
    sector: "ROOFING",
    rating: 4.8,
    reviewCount: 585,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Norske Electric",
    address: "3540 Kilkerry Ln #100, Hamel",
    phone: "(952) 443-4113",
    website: "norskeelectric.com",
    sector: "ELECTRICAL",
    rating: 5,
    reviewCount: 571,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Window Nation Minneapolis",
    address: "8862 W 35W Service Dr NE, Blaine",
    phone: "(612) 213-0485",
    website: "windownation.com",
    sector: "WINDOWS",
    rating: 4.5,
    reviewCount: 523,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Showcase Lawn Care",
    address: "9210 Wyoming Ave N #260, Brooklyn Park",
    phone: "(763) 425-1200",
    website: "lawn.pro",
    sector: "LANDSCAPING",
    rating: 4.8,
    reviewCount: 520,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Minnesota Tree Experts",
    address: "7527 Oliver Ave, Brooklyn Park",
    phone: "(763) 560-9616",
    website: "minnesotatreeexperts.com",
    sector: "LANDSCAPING",
    rating: 4.8,
    reviewCount: 507,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Aladdin Doors Inc.",
    address: "800 SE Washington Ave #205, Minneapolis",
    phone: "(612) 314-3040",
    website: "aladdindoors.com",
    sector: "GARAGE DOORS",
    rating: 4.9,
    reviewCount: 466,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Craftsmen Home Improvements",
    address: "7455 France Ave S #194, Edina",
    phone: "(952) 930-3777",
    website: "craftsmenhomeimprovements.com",
    sector: "GENERAL CONTRACTOR",
    rating: 5,
    reviewCount: 442,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Shared Solar Advisors USA",
    address: "3800 American Blvd W #1500, Bloomington",
    phone: "(952) 900-2837",
    website: "sharedsolaradvisors.com",
    sector: "SOLAR",
    rating: 5,
    reviewCount: 435,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Kaufman Roofing",
    address: "14330 Ewing Ave S, Burnsville",
    phone: "(612) 722-0965",
    website: "kaufmanroofing.com",
    sector: "ROOFING",
    rating: 4.8,
    reviewCount: 426,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Green Clean",
    address: "5301 E River Rd #115, Fridley",
    phone: "(612) 789-9600",
    website: "teamgreenclean.com",
    sector: "RESTORATION",
    rating: 4.9,
    reviewCount: 403,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Abra Kadabra Environmental",
    address: "1101 Pierce St NE, Minneapolis",
    phone: "(763) 645-5948",
    website: "abrakadabraenvironmental.com",
    sector: "RESTORATION",
    rating: 4.9,
    reviewCount: 381,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "KNO Woodworks",
    address: "4649 Bloomington Ave, Minneapolis",
    phone: "(612) 226-5172",
    website: "knowoodworks.com",
    sector: "GENERAL CONTRACTOR",
    rating: 5,
    reviewCount: 367,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Presidential Construction",
    address: "6885 Sycamore Ln N #220, Maple Grove",
    phone: "(651) 766-3464",
    website: "presidentialconstructioninc.com",
    sector: "GENERAL CONTRACTOR",
    rating: 5,
    reviewCount: 361,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Superior Fence & Rail",
    address: "5340 Quam Ave NE, St Michael",
    phone: "(763) 340-0010",
    website: "superiorfenceandrail.com",
    sector: "FENCING/DECKS",
    rating: 5,
    reviewCount: 358,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "The Brothers That Just Do Gutters",
    address: "7256 Commerce Cir E #A, Fridley",
    phone: "(763) 328-0118",
    website: "brothersgutters.com",
    sector: "ROOFING",
    rating: 4.9,
    reviewCount: 316,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Headwaters Painting",
    address: "1101 Stinson Blvd NE #102, Minneapolis",
    phone: "(612) 208-6383",
    website: "headwaterspainting.com",
    sector: "PAINTING",
    rating: 5,
    reviewCount: 311,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Five Star Bath Solutions",
    address: "3572 Hoffman Rd E, Vadnais Heights",
    phone: "(612) 261-0101",
    website: "fivestarbathsolutions.com",
    sector: "GENERAL CONTRACTOR",
    rating: 4.7,
    reviewCount: 282,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Bayport Roofing and Siding",
    address: "2240 Edgewood Ave S #201, St Louis Park",
    phone: "(612) 235-7663",
    website: "bayportroofing.com",
    sector: "ROOFING",
    rating: 4.6,
    reviewCount: 279,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Nordeast Electric",
    address: "4219 Central Ave NE, Minneapolis",
    phone: "(763) 789-4800",
    website: "nordeastelectric.com",
    sector: "ELECTRICAL",
    rating: 4.8,
    reviewCount: 276,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Rosebud Decks & Porches",
    address: "2275 McKnight Rd N #8, North St Paul",
    phone: "(651) 409-5606",
    website: "rosebudconstruction.com",
    sector: "FENCING/DECKS",
    rating: 4.9,
    reviewCount: 244,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Centauri Systems",
    address: "9278 Isanti St NE, Blaine",
    phone: "(763) 248-2734",
    website: "solarbycentauri.com",
    sector: "SOLAR",
    rating: 5,
    reviewCount: 176,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "American Sewer LLC",
    address: "9001 Emerson Ave S, Bloomington",
    phone: "(612) 246-4800",
    website: "americansewers.com",
    sector: "PLUMBING",
    rating: 4.8,
    reviewCount: 166,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Twin Cities Siding & Roofing",
    address: "1053 Grand Ave, St Paul",
    phone: "(651) 390-1806",
    website: "tcsidingprofessionals.com",
    sector: "ROOFING",
    rating: 4.9,
    reviewCount: 165,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Mid-State Seamless Gutters",
    address: "8401 73rd Ave N #44, Brooklyn Park",
    phone: "(612) 801-1151",
    website: "onegutter.com",
    sector: "ROOFING",
    rating: 4.8,
    reviewCount: 154,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "KRA Tree & Stump Services",
    address: "9731 4th Ave S, Bloomington",
    phone: "(612) 516-8118",
    website: "facebook.com/KRATree",
    sector: "LANDSCAPING",
    rating: 5,
    reviewCount: 149,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Skyline Electric",
    address: "2500 Cleveland Ave N #J, Roseville",
    phone: "(651) 504-3448",
    website: "skylineelectricmn.com",
    sector: "ELECTRICAL",
    rating: 4.9,
    reviewCount: 134,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Pro Window Repair & Service",
    address: "9101 Davenport St NE, Blaine",
    phone: "(612) 240-0772",
    website: "prowindowrepair.com",
    sector: "WINDOWS",
    rating: 5,
    reviewCount: 128,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Sela Gutter Connection",
    address: "3400 48th Ave N, Brooklyn Center",
    phone: "(612) 442-1080",
    website: "selagutterconnection.com",
    sector: "ROOFING",
    rating: 4.8,
    reviewCount: 126,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Mill City Concrete and Masonry",
    address: "1822 Monroe St NE, Minneapolis",
    phone: "(612) 723-3963",
    website: "millcityconcrete.com",
    sector: "CONCRETE",
    rating: 4.7,
    reviewCount: 126,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "iFlooring",
    address: "1710 Douglas Dr N #224V, Golden Valley",
    phone: "(612) 759-0620",
    website: "ifloormn.com",
    sector: "FLOORING",
    rating: 5,
    reviewCount: 125,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Dean Bjorkstrand Landscaping",
    address: "5508 Clinton Ave, Minneapolis",
    phone: "(612) 861-3919",
    website: "deanbjorkstrand.com",
    sector: "LANDSCAPING",
    rating: 4.9,
    reviewCount: 122,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Signature Electric Co",
    address: "4675 Balsam Ln N, Plymouth",
    phone: "(763) 588-0090",
    website: "signatureelectric.net",
    sector: "ELECTRICAL",
    rating: 4.8,
    reviewCount: 120,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Lifetime Garage Door Repair",
    address: "2920 Bryant Ave S #333, Minneapolis",
    phone: "(952) 333-4818",
    website: "lifetimegaragedoorrepair.com",
    sector: "GARAGE DOORS",
    rating: 4.9,
    reviewCount: 117,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "ONYX Plumbing & Gas",
    address: "6325 Cambridge St #7, Minneapolis",
    phone: "(612) 234-6699",
    website: "calltheonyx.com",
    sector: "PLUMBING",
    rating: 4.9,
    reviewCount: 115,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "US Solar Corporation",
    address: "323 N Washington Ave #350, Minneapolis",
    phone: "(612) 260-2230",
    website: "us-solar.com",
    sector: "SOLAR",
    rating: 4.6,
    reviewCount: 117,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "TruNorth Solar",
    address: "3735 Dunlap St N, Arden Hills",
    phone: "(612) 888-9599",
    website: "trunorthsolar.com",
    sector: "SOLAR",
    rating: 4.9,
    reviewCount: 71,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "MN Solar",
    address: "9841 13th Ave N, Plymouth",
    phone: "(320) 444-5696",
    website: "mnsolarandmore.com",
    sector: "SOLAR",
    rating: 4.9,
    reviewCount: 113,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Erik Nelson Plumbing LLC",
    address: "2617 37th Ave S, Minneapolis",
    phone: "(612) 242-6483",
    website: "eriknelsonplumbing.com",
    sector: "PLUMBING",
    rating: 4.9,
    reviewCount: 223,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Allstar Construction",
    address: "5145 Industrial St #103, Maple Plain",
    phone: "(763) 296-7771",
    website: "allstartoday.com",
    sector: "GENERAL CONTRACTOR",
    rating: 4.8,
    reviewCount: 219,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Hayes Window Restoration",
    address: "2508 24th Ave S, Minneapolis",
    phone: "(612) 259-7855",
    website: "hayeswindows.com",
    sector: "WINDOWS",
    rating: 5,
    reviewCount: 209,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Deck Science",
    address: "5200 Willson Rd, Edina",
    phone: "(612) 778-4141",
    website: "deckscience.com",
    sector: "FENCING/DECKS",
    rating: 5,
    reviewCount: 202,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Keyprime Roofing and Remodeling",
    address: "1000 Boone Ave N #760, Golden Valley",
    phone: "(952) 230-1269",
    website: "keyprimeroofing.com",
    sector: "ROOFING",
    rating: 4.9,
    reviewCount: 197,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Bedrock Restoration",
    address: "7000 Oxford St, St Louis Park",
    phone: "(612) 778-3044",
    website: "bedrockrestoration.com",
    sector: "RESTORATION",
    rating: 4.9,
    reviewCount: 193,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "A to Z Construction",
    address: "124 County Rd 81, Maple Grove",
    phone: "(612) 366-1386",
    website: "atoz-construction.com",
    sector: "ROOFING",
    rating: 5,
    reviewCount: 189,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Bold North Roofing and Contracting",
    address: "1620 W 98th St #100, Minneapolis",
    phone: "(952) 260-2293",
    website: "boldnorthroofing.com",
    sector: "ROOFING",
    rating: 5,
    reviewCount: 182,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "TWS Remodeling",
    address: "8616 Xylon Ave N #A, Minneapolis",
    phone: "(612) 353-5780",
    website: "twsremodeling.com",
    sector: "WINDOWS",
    rating: 4.5,
    reviewCount: 1033,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Grounded Earth",
    address: "603 Ontario St SE Unit 1, Minneapolis",
    phone: "(612) 223-6441",
    website: "groundedearthservices.com",
    sector: "LANDSCAPING",
    rating: 4.9,
    reviewCount: 119,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Brennan Heikes Professional Painting",
    address: "612 Morgan Ave S, Minneapolis",
    phone: "(612) 743-4458",
    website: "brennanheikespainting.com",
    sector: "PAINTING",
    rating: 5,
    reviewCount: 83,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Varsity Painters",
    address: "5416 Chicago Ave, Minneapolis",
    phone: "(952) 938-3886",
    website: "varsitypainters.com",
    sector: "PAINTING",
    rating: 4.9,
    reviewCount: 108,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Lakeside Floor Coverings",
    address: "7500 University Ave NE APT 1, Fridley",
    phone: "(763) 503-0100",
    website: "lakesidefloorcovering.com",
    sector: "FLOORING",
    rating: 4.8,
    reviewCount: 102,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Ridgeline Fence and Deck",
    address: "3463 Hiawatha Ave, Minneapolis",
    phone: "(612) 868-4879",
    website: "ridgelinefenceanddeck.com",
    sector: "FENCING/DECKS",
    rating: 5,
    reviewCount: 676,
    priority: "high",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Cedar Creek Energy",
    address: "3155 104th Ln NE, Blaine",
    phone: "(763) 432-5261",
    website: "cedarcreekenergy.com",
    sector: "SOLAR",
    rating: 4.9,
    reviewCount: 71,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
  {
    name: "Refuge Design & Landscape",
    address: "3021 10th Ave S, Minneapolis",
    phone: "(952) 236-4843",
    website: "refugemn.com",
    sector: "LANDSCAPING",
    rating: 4.9,
    reviewCount: 65,
    priority: "medium",
    isBonus: false,
    callType: "cold_call",
  },
];

function seedKey(name: string, callType: "walk_in" | "cold_call"): string {
  return `${name.toLowerCase()}::${callType}`;
}

export async function seedBusinesses(log: (msg: string) => void = () => {}): Promise<void> {
  const existing = await db
    .select({
      id: businessesTable.id,
      name: businessesTable.name,
      callType: businessesTable.callType,
    })
    .from(businessesTable);

  const existingByKey = new Map(
    existing.map((b) => [
      seedKey(b.name, b.callType as "walk_in" | "cold_call"),
      b.id,
    ])
  );

  // Determine which seed entries are missing so we can decide whether to run.
  const missingSeeds = BUSINESSES.filter(
    (b) => !existingByKey.has(seedKey(b.name, b.callType ?? "walk_in"))
  );

  if (missingSeeds.length === 0) {
    log(`Seed skipped — all ${BUSINESSES.length} seed entries already present (${existing.length} total rows)`);
    return;
  }

  log(`Seeding businesses (${missingSeeds.length} missing of ${BUSINESSES.length} seed entries; ${existing.length} rows in DB)...`);

  let inserted = 0;
  let updated = 0;

  for (const business of BUSINESSES) {
    const callType = business.callType ?? "walk_in";
    const existingId = existingByKey.get(seedKey(business.name, callType));
    if (existingId !== undefined) {
      await db
        .update(businessesTable)
        .set({
          address: business.address,
          phone: business.phone,
          website: business.website,
          sector: business.sector,
          rating: business.rating,
          reviewCount: business.reviewCount,
          mapsUrl: business.mapsUrl,
          priority: business.priority,
          routeDay: business.routeDay ?? null,
          isBonus: business.isBonus,
          buildingGroup: business.buildingGroup ?? null,
          callType,
        })
        .where(eq(businessesTable.id, existingId));
      updated++;
    } else {
      await db.insert(businessesTable).values({ ...business, callType });
      inserted++;
    }
  }

  log(`Seed complete — inserted: ${inserted}, updated: ${updated}`);
}

